--- #YAML:1.0
name:               POE-Component-Client-HTTP
version:            0.895
abstract:           Non-blocking/concurrent HTTP queries with POE
author:
    - Rocco Caputo <rcaputo@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    HTTP::Request:        1.3
    HTTP::Response:       1.37
    Net::HTTP::Methods:   0.02
    POE:                  1.28
    POE::Component::Client::Keepalive:  0.261
    Test::POE::Server::TCP:  0
    URI:                  1.24
resources:
    license:     http://dev.perl.org/licenses/
    repository:  http://github.com/rcaputo/poe-component-client-http
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
