--- #YAML:1.0
name:               POE-Component-Client-HTTP
version:            0.87
abstract:           Non-blocking/concurrent HTTP queries with POE
author:
    - Rocco Caputo <rcaputo@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    HTTP::Request:        1.3
    HTTP::Response:       1.37
    Net::HTTP::Methods:   0.02
    POE:                  0.3202
    POE::Component::Client::Keepalive:  0.25
    Test::POE::Server::TCP:  0
    URI:                  1.24
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
