--- #YAML:1.0
name:                POE-Component-Client-HTTP
version:             0.74
abstract:            Non-blocking/concurrent HTTP queries with POE
license:             unknown
generated_by:        ExtUtils::MakeMaker version 6.30_01
author:              Rocco Caputo <rcaputo@cpan.org>
distribution_type:   module
requires:     
    HTTP::Request:                 1.3
    HTTP::Response:                1.37
    POE:                           0.31
    POE::Component::Client::Keepalive: 0.04
    URI:                           1.24
meta-spec:
    url: <http://module-build.sourceforge.net/META-spec-new.html>;
    version: 1.1
