--- #YAML:1.0
name:                POE-Component-Client-HTTP
version:             0.81
abstract:            Non-blocking/concurrent HTTP queries with POE
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
    HTTP::Request:                 1.3
    HTTP::Response:                1.37
    Net::HTTP::Methods:            0.02
    POE:                           0.3202
    POE::Component::Client::Keepalive: 0.09
    URI:                           1.24
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Rocco Caputo <rcaputo@cpan.org>
